### ISSUE TITLE
IsSatisfiedBy as extension method

### ISSUE THREAD

**Issue by vosarat** [joakimjm/specification#1]
The idea of this suggestion is to minify the ISpecification interface to:

`public interface ISpecification<T>
{
        Expression<Func<T, bool>> ToExpression();
}`

and have `IsSatisfiedBy` as extension method instead of base abstract implementation. Benefits I see in this approach is following:

1. Interface cannot be misimplemented, meaning that `IsSatisifedBy` is granted to have exactly same behaviour as underlying expression. Now a class implementing interface can have two completely different implementation for this methods.
2. In unit testing we known exactly what we ought to mock. Now we can occasionally mock `IsSatisfiedBy` when the class to which we pass mocked `ISpecification` actually uses `ToExpression`.

**Comment by joakimjm** [comment]
It's a good idea, however the problem with only having the option implement by expression means you _have_ to compile that expression to use the specification.

I have use cases where I combine specifications dynamically. Relying on expressions in those cases cause a huge JIT compilation performance overhead. We measured more than 60% time spent compiling, but we had the option to implement IsSatisfiedBy from the interface to rely on Func directly.

I'm still thinking about how to support this use case from the library, and am open to suggestions.

Sorry about the delayed answer.

**Comment by joakimjm** [comment]
I've refactored the internal specifications a bit to solve the performance issues of using the previous Expression-driven approach. It however removes the option to simplify the interface itself, as you suggested. 

I'm open for other solutions, if you have any ideas on how to solve both problems.

**Comment by vosarat** [comment]
In the end, I came to consulsion that current solution is the best solution we could have. Recently I found myself in position where I need to have specification without actual expression (because it have a statement body). So I think that reason along with performance concern is more important, then benefits from my original suggestion.

Thanks for replying
